- name: Initialize Kubernetes control plane
  hosts: masters
  become: yes
  tasks:

    - name: Initialize the Kubernetes cluster with containerd
      command: >
        kubeadm init
        --pod-network-cidr=192.168.0.0/16
        --cri-socket=unix:///run/containerd/containerd.sock
      register: kubeadm_init
      changed_when: "'Your Kubernetes control-plane has initialized' in kubeadm_init.stdout"
      # Optional: you can ignore warnings about already initialized cluster
      ignore_errors: yes

    - name: Create .kube directory for kubectl config
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: '0644'

    - name: Install Calico CNI
      command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"

    - name: Extract kubeadm join command for workers
      set_fact:
        kubeadm_join_command: "{{ kubeadm_init.stdout_lines
          | select('search', 'kubeadm join')
          | list | join(' ') }}"
      when: kubeadm_init is defined